[build]
  command = "pnpm install && pnpm build"
  publish = "dist"
  functions = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@p-stream/providers", "cheerio"]
